### ISSUE TITLE
create_spike_sprays error 

### ISSUE THREAD

**Issue by jamesjun** [flatironinstitute/spikeforest2#18]
```
$ working/runs/2020_03_12a/005_generate_unit_details.sh

Traceback (most recent call last):
  File "./generate_unit_details.py", line 348, in <module>
    main()
  File "./generate_unit_details.py", line 151, in main
    sr['spike_spray_results'] = spike_spray_results
  File "/mnt/home/jjun/src/spikeforest2/hither/_core.py", line 90, in __exit__
    wait()
  File "/mnt/home/jjun/src/spikeforest2/hither/_core.py", line 539, in wait
    raise Exception(f'Error running job: {_label}')
Exception: Error running job: create_spike_sprays
```

**Comment by jamesjun** [comment]
Here is another one when I ran `working/runs/2020_03_31a/all.sh`

===== Hither: Found cached result for [compute-recording-info:paired_crcns/d18011_d18011.004]
#############################################################
===== Hither: finished [create_spike_sprays] with status finished after 3.9326891899108887 sec
Stopping worker.
===== Hither: running [create_spike_sprays] in container: docker://magland/spikeforest2:0.1.0
#############################################################

                #!/bin/bash

                exec singularity exec -e  \
                    -B $KACHERY_STORAGE_DIR:/kachery-storage \
                    -B /mnt/ceph/users/jjun/.kachery/tmp/tmp_hither_run_in_container_create_spike_sprays_sxix5pm7:/run_in_container \
                    -B /mnt/ceph/users/jjun/.kachery/sha1/67/6b/92/676b928a9c4dec072f60c7e4f41d376a6e068e33:/inputs/firings_sorted -B /mnt/ceph/users/jjun/.kachery/sha1/53/3b/4f/533b4f1cf3d87c0cfd12ba241de0e61bb405b5c1:/inputs/firings_true.mda -B /mnt/ceph/users/magland/kachery-storage/sha1/b5/5e/92/b55e923214a7b1874f28fd5a3a94d07ca75b2a1d:/inputs/filtered_timeseries -B /mnt/ceph/users/jjun/.kachery/tmp/tmp_hither_run_in_container_create_spike_sprays_sxix5pm7/outputs:/outputs \
                    docker://magland/spikeforest2:0.1.0 \
                    bash /run_in_container/run.sh

#############################################################
===== Hither: finished [create_spike_sprays] with status finished after 4.1734702587127686 sec
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Stopping worker.
Done cleaning up job handlers.
Traceback (most recent call last):
  File "./generate_unit_details.py", line 348, in <module>
    main()
  File "./generate_unit_details.py", line 151, in main
    sr['spike_spray_results'] = spike_spray_results
  File "/mnt/home/jjun/src/spikeforest2/hither/_core.py", line 90, in __exit__
    wait()
  File "/mnt/home/jjun/src/spikeforest2/hither/_core.py", line 539, in wait
    raise Exception(f'Error running job: {_label}')
Exception: Error running job: create_spike_sprays
