### ISSUE TITLE
container creation failed

### ISSUE THREAD

**Issue by jamesjun** [flatironinstitute/spikeforest2#2]
```
(spikeforest2) jjun@ccmlin000:examples$ python example_ironclust.py 
===== Hither: running ironclust in container: docker://magland/sf-ironclust:5.0.5
FATAL:   container creation failed: mount ->/mnt/home/jjun/.kachery error: can't remount /mnt/home/jjun/.kachery: no such file or directory
Traceback (most recent call last):
  File "example_ironclust.py", line 14, in <module>
    sorting_out=hither.File()
  File "/mnt/home/jjun/src/spikeforest2/hither/_core.py", line 180, in run
    local_modules=local_modules
  File "/mnt/home/jjun/src/spikeforest2/hither/_run_function_in_container.py", line 189, in run_function_in_container
    raise Exception('Non-zero exit code ({}) running {} in container {}'.format(retcode, name, container))
Exception: Non-zero exit code (255) running ironclust in container docker://magland/sf-ironclust:5.0.5
(spikeforest2) jjun@ccmlin000:examples$ echo $KACHERY_STORAGE_DIR
/mnt/home/jjun/.kachery
```

**Comment by magland** [comment]
Okay I think I fixed that. Please re-pull and try again.
J

**Comment by jamesjun** [comment]
It worked using singularity after `module load singularity` on our workstation.
