### ISSUE TITLE
fragmented instructions: spikeforest_widgets installation

### ISSUE THREAD

**Issue by nahawtho** [flatironinstitute/spikeforest2#22]
the spikeforest_widgets installation instructions appear fragmented or repeated. There is one set of instructions at flatironinstitute/spikeforest2/README.md . This set of instructions is written like it is all you need to install spikeforest_widgets, but there seems to be more complete instructions at  spikeforest2/spikeforest_widgets/generated/docs/install.md  which I had to click around to find. Perhaps the first set of instructions is supposed to work on its own (and I am having an unexpected error), but it does not even have a line with "pip install --upgrade spikeforest_widgets".  

Anyways, here's my error following the instructions at flatironinstitute/spikeforest2/README.md :

`>>> import spikeforest_widgets as sw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/home/Desktop/code/spikeforest2/spikeforest_widgets/generated/spikeforest_widgets/spikeforest_widgets/__init__.py", line 7, in <module>
    from .all_widgets import *
  File "/Users/home/Desktop/code/spikeforest2/spikeforest_widgets/generated/spikeforest_widgets/spikeforest_widgets/all_widgets.py", line 6, in <module>
    from .BaseWidget import _BaseWidget
  File "/Users/home/Desktop/code/spikeforest2/spikeforest_widgets/generated/spikeforest_widgets/spikeforest_widgets/BaseWidget.py", line 221
    def host(self, *, port):
                    ^
SyntaxError: invalid syntax`
(the carrot indicating the syntax error appears under the 2nd comma in "host(self, *, port)" for me)

I expect I am about to fix this following instructions at spikeforest2/spikeforest_widgets/generated/docs/install.md next, but I thought I'd let u know this may be confusing for others as well.

I am excited to get this running; thanks for all your hard work!

**Comment by magland** [comment]
Hi thanks for the report and sorry for the confusion. Unfortunately spikeforest widgets is an old approach to what we are trying to do with labbox-ephys (early stage of development). I suggest you use spikewidgets for now: https://github.com/SpikeInterface/spikewidgets

**Comment by nahawtho** [comment]
Ok. No worries. Thanks for the clarification @magland
