### ISSUE TITLE
MS4 container creation error creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists.

### ISSUE THREAD

**Issue by nahawtho** [flatironinstitute/spikeforest2#24]
Is it possible the container already has a localtime file? It appears the Makefile is trying to map in something that already exists. I do not know if the localtime mapping ( -v /etc/localtime:/etc/localtime:ro ) is necessary ? If so maybe make sure to delete the old localtime file when creating the image? 

`sf2env) home@Mes-MacBook-Pro examples % python3 example_mountainsort4.py
===== Hither: running [mountainsort4] in container: docker://magland/sf-mountainsort4:0.3.2`
#############################################################

                #!/bin/bash

                exec docker run --name Iyoclvbu_mountainsort4 -i  \
                    -v /etc/localtime:/etc/localtime:ro \
                    -v /etc/passwd:/etc/passwd -u 'id -u':'id -g' \
                    -v $KACHERY_STORAGE_DIR:/kachery-storage \
                    -v /Users/home/Desktop/code/spikeforest2/spikeforest2_container/spikeforest2/examples/tmp/tmp_hither_run_in_container_mountainsort4_idqqj5bm:/run_in_container \
                    -v /tmp:/tmp \
                    -v $HOME:$HOME \
                    -v /Users/home/Desktop/code/spikeforest2/spikeforest2_container/spikeforest2/examples/tmp/tmp_hither_run_in_container_mountainsort4_idqqj5bm/outputs:/outputs \
                    magland/sf-mountainsort4:0.3.2 \
                    bash /run_in_container/run.sh
                
#############################################################
`docker: Error response from daemon: error while creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists.
ERRO[0000] error waiting for container: context canceled 
Traceback (most recent call last):
  File "example_mountainsort4.py", line 14, in <module>
    sorting_out=hither.File()
  File "/Users/home/Desktop/code/spikeforest2/hither_sf/_core.py", line 271, in run
    _run_job(job)
  File "/Users/home/Desktop/code/spikeforest2/hither_sf/_core.py", line 464, in _run_job
    timeout=_job_timeout
  File "/Users/home/Desktop/code/spikeforest2/hither_sf/_run_function_in_container.py", line 263, in run_function_in_container
    raise Exception('Non-zero exit code ({}) running [{}] in container {}'.format(retcode, label, container))
Exception: Non-zero exit code (125) running [mountainsort4] in container docker://magland/sf-mountainsort4:0.3.2`

`(sf2env) home@Mes-MacBook-Pro examples % python3 --version
Python 3.7.7
(sf2env) home@Mes-MacBook-Pro examples % docker --version
Docker version 19.03.8, build afacb8b`

<img width="571" alt="Screen Shot 2020-06-19 at 11 52 33 AM" src="https://user-images.githubusercontent.com/28117852/85171211-6b2e0900-b223-11ea-88a8-16b0f814b008.png">
^ I tried adding /etc/localtime to make sure I can support mounting those files but I don't think that's the issue. There's probably something obvious i'm missing... thanks!

**Comment by nahawtho** [comment]
I realize now I failed to actually mount a directory, so if anyone has this issue, you may need to do this, mounting /etc and /private/etc instead:
<img width="569" alt="Screen Shot 2020-06-19 at 12 12 00 PM" src="https://user-images.githubusercontent.com/28117852/85172657-6028a800-b226-11ea-8521-48c1d98fb236.png">

**Comment by nahawtho** [comment]
now this is my issue 
`(sf2env) home@Mes-MacBook-Pro examples % chmod 777 ms4Out `
`(sf2env) home@Mes-MacBook-Pro examples % export KACHERY_STORAGE_DIR=/Users/home/Desktop/code/spikeforest2/examples/ms4Out`
`(sf2env) home@Mes-MacBook-Pro examples % python3 example_mountainsort4.py`
`===== Hither: running [mountainsort4] in container: docker://magland/sf-mountainsort4:0.3.2`
`#############################################################`
                #!/bin/bash

                exec docker run --name bTimFZai_mountainsort4 -i  \
                    -v /etc/localtime:/etc/localtime:ro \
                    -v /etc/passwd:/etc/passwd -u `id -u`:`id -g` \
                    -v $KACHERY_STORAGE_DIR:/kachery-storage \
                    -v /Users/home/Desktop/code/spikeforest2/examples/ms4Out/tmp/tmp_hither_run_in_container_mountainsort4_a6a909h8:/run_in_container \
                    -v /tmp:/tmp \
                    -v $HOME:$HOME \
                    -v /Users/home/Desktop/code/spikeforest2/examples/ms4Out/tmp/tmp_hither_run_in_container_mountainsort4_a6a909h8/outputs:/outputs \
                    magland/sf-mountainsort4:0.3.2 \
                    bash /run_in_container/run.sh
`#############################################################`
`docker: Error response from daemon: Mounts denied: EOF.
ERRO[0000] error waiting for container: context canceled 
Traceback (most recent call last):
  File "example_mountainsort4.py", line 14, in <module>
    sorting_out=hither.File()
  File "/Users/home/Desktop/code/spikeforest2/hither_sf/_core.py", line 271, in run
    _run_job(job)
  File "/Users/home/Desktop/code/spikeforest2/hither_sf/_core.py", line 464, in _run_job
    timeout=_job_timeout
  File "/Users/home/Desktop/code/spikeforest2/hither_sf/_run_function_in_container.py", line 263, in run_function_in_container
    raise Exception('Non-zero exit code ({}) running [{}] in container {}'.format(retcode, label, container))
Exception: Non-zero exit code (125) running [mountainsort4] in container docker://magland/sf-mountainsort4:0.3.2
(sf2env) home@Mes-MacBook-Pro examples %   `
