### ISSUE TITLE
Error running the tridesclous sorter

### ISSUE THREAD

**Issue by teristam** [flatironinstitute/spikeforest2#32]
Hi,

I am trying to run the example `example_tridesclous.py` . However, it reported an error

`===== Hither: finished [tridesclous] with status error after 1.8500285148620605 sec`

I checked the docker logs, and it showed this error

```
libgomp: Invalid value for environment variable OMP_NUM_THREADS
tridesclous 2021-01-26T22:47:45.862631: Traceback (most recent call last):
tridesclous 2021-01-26T22:47:45.862659:   File "/run_in_container/run.py", line 15, in main
tridesclous 2021-01-26T22:47:45.862664:     retval = tridesclous(**kwargs)
tridesclous 2021-01-26T22:47:45.862669:   File "/run_in_container/function_src/_tridesclous.py", line 36, in tridesclous
tridesclous 2021-01-26T22:47:45.862673:     sorter.set_params(
tridesclous 2021-01-26T22:47:45.862677:   File "/usr/local/lib/python3.6/dist-packages/spikesorters/basesorter.py", line 109, in set_params
tridesclous 2021-01-26T22:47:45.862680:     self._dump_params()
tridesclous 2021-01-26T22:47:45.862684:   File "/usr/local/lib/python3.6/dist-packages/spikesorters/basesorter.py", line 116, in _dump_params
tridesclous 2021-01-26T22:47:45.862687:     params['recording'] = recording.make_serialized_dict()
tridesclous 2021-01-26T22:47:45.862691:   File "/usr/local/lib/python3.6/dist-packages/spikeextractors/baseextractor.py", line 46, in make_serialized_dict
tridesclous 2021-01-26T22:47:45.862693:     'key_properties': self._key_properties, 'version': imported_module.__version__,
tridesclous 2021-01-26T22:47:45.862702: AttributeError: module 'spikeforest2_utils' has no attribute '__version__'
tridesclous 2021-01-26T22:47:44.012691: ###### RUNNING: tridesclous
tridesclous 2021-01-26T22:47:45.858163: Sorting...
```
Any idea how to resolve this? Thanks!

**Comment by ChrisCurrin** [comment]
I had the same error.

To solve, I followed the instructions in https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package#459185

That is, in `spikeforest2_utils` folder I add a `_version.py` file with contents
```python
__version__ = '0.1.0' # the version as in setup.py
```

In the `spikeforest2_utils.__init__.py` file I add 
```python
... # other lines
from ._version import __version__
```

I did `pip install -e .` again (from spikeforest2 root dir), but this may not be necessary.

Then 
```bash 
python examples/example_tridesclous.py 
```
